name: appzap_counter_web_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.8+9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_inappwebview: ^6.0.0
  flutter_esc_pos_network: ^1.0.3
  image: ^4.1.7
  esc_pos_utils_plus: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_appzap.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/logo/
    

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
